# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wger.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mealitem',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='mealitem',
            name='time',
            field=wger.utils.fields.Html5TimeField(blank=True, null=True, verbose_name='Time (approx)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='license_author',
            field=models.ForeignKey(blank=True, help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Declined'), ('4', 'Submitted by administrator'), ('5', 'System ingredient')], default='1', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='meal',
            name='order',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='order',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Order'),
        ),
    ]
