# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-19 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20171019_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='license_author',
            field=models.ForeignKey(blank=True, help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Author', to_field='name', verbose_name='Author'),
        ),
    ]
