# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
          
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt && pip install -r requirements_devel.txt
            ROOT=$(pwd)
            invoke create-settings  --settings-path $ROOT/settings.py --database-path $ROOT/database.sqlite
            ./manage.py makemigrations

            ROOT=$(pwd)
            invoke create-settings  --settings-path $ROOT/settings.py --database-path $ROOT/database.sqlite
            #invoke bootstrap-wger --settings-path $ROOT/settings.py --no-start-server

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports