# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171006_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='These are the users that have been added viathe rest api', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile', verbose_name='Added by external via rest api'),
        ),
    ]
