# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171019_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysofweek',
            name='the_type',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
