# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20171019_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='cycle',
            field=models.CharField(choices=[('Microcycle', 'Microcycle - Up to one week'), ('Mesocycle', 'Mesocycle - Two to six weeks'), ('Macrocycle', 'Macrocycle - Up to one year')], default='Microcycle', max_length=10),
        ),
    ]
